import Footer from "./components/Shared/Footer";
import Header from "./components/Shared/Header";
import Fixed_footer from "./components/Shared/Fixed_footer";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "RO",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
        <Fixed_footer />
      </body>
    </html>
  );
}
